### ISSUE TITLE
Notes loading infinitely on Linux app

### ISSUE THREAD

**Issue by Candyhands** [PhieF/CarnetElectron#57]
Lol, I'm so sorry. I know you  just fixed the login issue, and now I can log in. But I am unable to edit any of my notes in the app. This is using the most recent 64 bit app image on framagit, and the issue exists on both my PopOS and Manjaro machines. Thank you for keeping the support up.

**Comment by brainstormtrooper** [comment]
Same issue on openSUSE 64 bit

**Comment by brainstormtrooper** [comment]
This file is created in the folder containing the appimage when trying to edit a note (I added the .txt extension in order to attach the file).
[reader.html.txt](https://github.com/CarnetApp/CarnetElectron/files/8130097/reader.html.txt)
I don't know if it makes a difference, but there's an error in the HTML syntax - what should be a closing </html> tag is replaced by a second </head> tag at the end of the file.

There doesn't seem to be anything in the system logs...

**Comment by brainstormtrooper** [comment]
https://github.com/CarnetApp/CarnetElectron/blob/main/reader/reader.html

**Comment by brainstormtrooper** [comment]
yup, that fixed it... 
I cloned the repo, fixed the html, and rebuilt the app. It works fine :-)

**Comment by barbicane** [comment]
![image](https://user-images.githubusercontent.com/16447680/167107309-da7aed94-bab0-4871-8acc-1139fa3cf1a4.png)
hi ! same issue for me on ZorinOS 16 with AppImage64.

**Comment by barbicane** [comment]
> ![image](https://user-images.githubusercontent.com/16447680/167107309-da7aed94-bab0-4871-8acc-1139fa3cf1a4.png) hi ! same issue for me on ZorinOS 16 with AppImage64.

Solved by building a new version from source !

**Comment by mohammadrafigh** [comment]
any updates?

**Comment by tomvdyck** [comment]
I downloaded a new app image today to make sure it would not be because of an older version. But the same issue remains: cannot open/edit a note.

**Comment by jurgen-74** [comment]
> > hi ! same issue for me on ZorinOS 16 with AppImage64.
> 
> Solved by building a new version from source ! (edit: i don't know why but you have to launch once in "dev mode" with `npm start ` after installed node (with nvm for me) and electron. after that, the edit mode will work when packaged as Appimage.)

Could you share the new AppImage64 with us?
